25 absence UI
oXyut/check-attendance-docker pull request #33
Opened 2023-12-31 19:45 UTC by Leo-Ando

## やったこと

### 公欠の登録ページのUIの作成
* [next_app/src/app/absence/[userId]/page.tsx]に作成した
- 日付、公欠理由を入力して公欠を登録するフォームを作成した 
  - 日付を選ぶカレンダーはreact-multi-date-pickerをしようした。
  - 同じ公欠理由で複数日を登録できるようにした
  - 日付か理由のどちらか一方が空だと登録ボタンが押せないようにした
- 公欠一覧を表示する表を作成した
   - 日付が過ぎるとチェックマークがつき、その行の色が薄くなるようにした
   - 日付が過ぎていない行は削除ボタンを表示し、押すとポップアップで削除をするか選べるようにした。削除をすると、データベースからその公欠のデータが削除される。
   - 10件ごとに表示し、矢印で次の表に遷移するようにした
   - 理由は途中で省略するようにした
   
### api/absence/route.tsの変更
* 同じ理由で複数日の公欠を登録できるようにした
* DELETEで公欠を削除できるようにした

### api/user/route.tsの変更
*  api/absence/route.tsで削除する公欠のidを取得するため、absencesの要素にidを追加した

## やらないこと
* 無し

## できるようになること（ユーザ目線）

* 公欠の登録、公欠の一覧表示ができるようになる

## できなくなること（ユーザ目線）

* 無し

## 動作確認
### [next_app/src/app/absence/[userId]/page.tsx]ページを表示した
* 公欠登録フォーマットで同じ理由で複数日登録したところ、データベースに公欠が登録された
* 公欠登録フォーマットは日付か理由のどちらか一方が空だと登録ボタンが押せなかった
- 予約一覧の表に公欠の一覧が表示された
  - 公欠理由は途中で省略された
  - 日付が過ぎるとチェックマークがついた
  - 削除ボタンを押すとポップアップが表示され、はいを押すとデータベースから公欠が削除された

2024-01-01 09:30 UTC, oXyut requested changes
以下の点を修正してください
- 画面サイズによっては日付入力フォームと理由入力フォームが同じ行に表示されることがあります。改行してください
- 日付入力フォームのカレンダーで複数日付を入力したあとに別のところを触ると入力がキャンセルされることがあります。これが仕様かどうかはわからないのですが、ユーザは困惑すると思うので何かしらの修正をしてほしいです
- absenceをPOSTしたあと、ページをリフレッシュしなくても表が更新されるようにしてください

2024-01-03 14:51 UTC, Leo-Ando commented
レビューありがとうございます。
修正し、pushしたので、確認よろしくお願いします。

2024-01-03 22:54 UTC, oXyut commented
- ページをリフレッシュせずにGETし直すやり方探してくれてありがとうございます。これ他のページにも適用させた方がいいですね。時間があるときにissue切ります
- カレンダーアイコンですが、クリックできないのであれば、日付入力テキストボックスの左にもって来たほうがいいかなと思います
- 日付入力フォームと理由入力フォームの外枠の太さと色が違うのが気になりました（ライトモードとダークモードの両方）

2024-01-04 13:41 UTC, Leo-Ando commented
修正完了しました。
* カレンダーアイコンを日付選択フォームの左に配置しました
* 理由入力フォームのクリックしていないときの外枠の太さと色を日付入力フォームにあわせました
* 日付入力フォームと理由入力フォームをクリックすると外枠が太くなるようにしました

確認よろしくお願いします。

2024-01-04 23:06 UTC, oXyut approved these changes

2024-01-04 23:17 UTC, oXyut requested changes
- 既に登録してある公欠の日付と同じ日付を登録できてしまいます。リロードしたら消えるので、POSTは問題なく、フロントの問題だと思います。現状のコードだと、GETし直したデータを表示するのではなく、フロント側で仮の更新をかけているように見えます。多分GETし直した方が簡潔になるので、その方向で修正をお願いできますか。
- テキストボックスの初期値に"公欠理由を記述（例：帰省）"が入っているのが気になります。ここは空白にして、初期状態ではButtonが押せないようにしたいです。レビューにも書きましたが、"公欠理由を記述（例：帰省）"を初期値に入れるのではなく、初期値は空白にして、テキストボックスにうすく"公欠理由を記述（例：帰省）"と表示させて、入力し始めたら消える、みたいな仕様にできませんか？

2024-01-04 23:17 UTC, oXyut commented on next_app/src/app/absence/[userId]/page.tsx
> +      });
```suggestion
      queryClient.invalidateQueries({ queryKey: ["absences", userId] });
```
で問題ないかと思います。

2024-01-04 23:17 UTC, oXyut commented on next_app/src/app/absence/[userId]/page.tsx
> +    },
こういう風にするのではなく、GETし直したデータを入れるようにできますか？

2024-01-04 23:17 UTC, oXyut commented on next_app/src/app/absence/[userId]/page.tsx
> +  const [absenceReason, setAbsenceReason] = useState("公欠理由を記述（例：帰省）");
"公欠理由を記述（例：帰省）"を初期値に入れるのではなく、初期値は空白にして、テキストボックスにうすく"公欠理由を記述（例：帰省）"と表示させて、入力し始めたら消える、みたいな仕様にできませんか？

2024-01-05 05:57 UTC, Leo-Ando commented
修正しました。レビューお願いします。

2024-01-05 13:00 UTC, oXyut approved these changes

2024-01-05 13:00 UTC, merged